theme: jekyll-theme-minimal

# Site wide configuration

title: Academic Website of Artun Dalyan
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Artun Dalyan
  avatar: Bio-photo.jpeg
  bio: "Resume"
  email: artundalyan21@berkeley.edu
  # Do not include the @ symbol in your Twitter username
  twitter: swimmerART
  linkedin: #username
  github: swimmerART
 
